---
name: 'Flux diff'
description: 'Run flux diff to see what changes would be applied to the cluster'
author: 'Kristain S.S'
runs:
  using: "composite"
  steps:
    # - name: Setup YQ
    #   uses: mikefarah/yq@v4
    - name: Setup YQ
      run: |
        wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq && chmod +x /usr/bin/yq
      shell: bash
    - name: Setup Flux CLI
      uses: fluxcd/flux2/action@main
    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
    - name: Run flux-diff.sh
      run: ${{ github.action_path }}/flux-diff.sh
      shell: bash
