---
name: 'Flux diff'
description: 'Run flux diff to see what changes would be applied to the cluster'
author: 'Kristain S.S'
outputs:
  diff-output:
    description: "Flux diff output"
    value: ${{ steps.set-output.outputs.diff-output }}
runs:
  using: "composite"
  steps:
    - name: Setup YQ
      run: |
        sudo curl -sL https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -o /usr/local/bin/yq
        sudo chmod +x /usr/local/bin/yq
      shell: bash
    - name: Setup Flux CLI
      uses: fluxcd/flux2/action@main
    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
    - name: Run flux-diff.sh
      run: ${{ github.action_path }}/flux-diff.sh
      shell: bash
    - name: Set diff output as action output
      shell: bash
      id: set-output
      run: |
        DIFF_OUTPUT=$(cat diff-output.txt)
        echo "diff-output<<EOF" >> $GITHUB_OUTPUT
        echo "$DIFF_OUTPUT" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT