---
name: 'Flux diff'
description: 'Run flux diff to see what changes would be applied to the cluster'
author: 'SPV'
inputs:
  path-filter:
    description: "Path to filter the flux diff. Comma separated string. E.g. 'some/path1,**/path2/*'"
    required: true
    default: "."
  autodetect-ignore-tenants:
    description: "Enable autodetect Flux tenants to ignore in the flux diff. It will look for new sync.yaml files in /tenant folder and assumes the sync.yaml contains a `apiVersion: kustomize.toolkit.fluxcd.io/v1 kind: Kustomization` object. The name of that object is used as tenant name."
    required: false
    default: "true"
  additional-ingore-tenants:
    description: "Flux tenants to ignore in the flux diff. Comma separated string. E.g. 'tenant1,tenant2'"
    required: false
    default: ""
outputs:
  diff-output:
    description: "Flux diff output"
    value: ${{ steps.set-output.outputs.diff-output }}
runs:
  using: "composite"
  steps:
    - name: Setup YQ
      run: |
        sudo curl -sL https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -o /usr/local/bin/yq
        sudo chmod +x /usr/local/bin/yq
      shell: bash
    - name: Setup Flux CLI
      uses: fluxcd/flux2/action@main
    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
    - name: Run flux-diff.sh
      run: |
        PATH_FILTER=${{ inputs.path-filter }} \
        AUTODETECT_IGNORE_TENANTS=${{ inputs.autodetect-ignore-tenants }} \
        IGNORE_TENANTS=${{ inputs.additional-ignore-tenants }} \
        ${{ github.action_path }}/flux-diff.sh
      shell: bash
    - name: Set diff output as action output
      shell: bash
      id: set-output
      run: |
        DIFF_OUTPUT=$(cat diff-output.txt)
        echo "diff-output<<EOF" >> $GITHUB_OUTPUT
        echo "$DIFF_OUTPUT" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT