---
name: 'Flux diff'
description: 'Run flux diff to see what changes would be applied to the cluster'
author: 'Kristain S.S'
runs:
  using: "composite"
  steps:
    - name: Run flux-diff.sh
      run: flux-diff.sh
      shell: bash
